### ISSUE TITLE
The VNC client SSH connection requires a key be present, although it is not used

### ISSUE THREAD

**Issue by flawedmatrix** [pivotal-cf-experimental/remote-pairing-release#4]
We check the username (which is the token in the VNC client SSH connection) in `PublicKeyCallback`. The callback is only called, when there is an SSH key present. Can we avoid this?

**Comment by coreyti** [comment]
This can be resolved by using `KeyboardInteractiveCallback` for token-based sessions.

**Comment by coreyti** [comment]
Fixed with https://github.com/pivotal-cf-experimental/remote-pairing-release/commit/d8b907f875ef61f1e676558b1a960c9cf8a40d2f
